'use strict';

const fs   = require('fs').promises;
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { query } = require('../config/database');

const execFileAsync = promisify(execFile);

const NGINX_DIR = path.join(__dirname, '..', '..', 'nginx');

// One server{} block per project, included at the nginx http{} level.
// ONE-TIME SETUP: symlink into sites-enabled so nginx picks it up automatically:
//   sudo ln -sf /home/zajako/nodeDeploy/nginx/projects.conf \
//               /etc/nginx/sites-enabled/nodedeploy-projects.conf
const NGINX_PROJECTS_CONF = process.env.NGINX_PROJECTS_CONF ||
  path.join(NGINX_DIR, 'projects.conf');

// Projects are served at <name>.<BASE_DOMAIN>
const BASE_DOMAIN = process.env.BASE_DOMAIN || 'npmdeploy.com';

// Full path to the wildcard cert directory (e.g. /etc/letsencrypt/live/npmdeploy.com-0001).
// Set WILDCARD_CERT_PATH to the exact path certbot printed, or set WILDCARD_CERT_DOMAIN
// to derive the path as /etc/letsencrypt/live/<domain>.
// Leave both empty to generate HTTP-only blocks until the cert is ready.
const WILDCARD_CERT_DOMAIN = process.env.WILDCARD_CERT_DOMAIN || '';
const WILDCARD_CERT_PATH = process.env.WILDCARD_CERT_PATH ||
  (WILDCARD_CERT_DOMAIN ? `/etc/letsencrypt/live/${WILDCARD_CERT_DOMAIN}` : '');

// -------------------------------------------------------------------------
// Build a server block for one project at <name>.<BASE_DOMAIN>
// No path-prefix stripping needed — the app runs at the root of its subdomain.
// WebSocket connections to wss://<name>.BASE_DOMAIN/ route correctly with no patching.
// -------------------------------------------------------------------------
function serverBlock(project) {
  const { name, port } = project;
  const serverName = `${name}.${BASE_DOMAIN}`;

  const location = `    location / {
        proxy_pass            http://127.0.0.1:${port};
        proxy_http_version    1.1;
        proxy_set_header      Upgrade           $http_upgrade;
        proxy_set_header      Connection        "upgrade";
        proxy_set_header      Host              $host;
        proxy_set_header      X-Real-IP         $remote_addr;
        proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_read_timeout    120s;
        proxy_connect_timeout 10s;
    }`;

  if (WILDCARD_CERT_PATH) {
    const certDir = WILDCARD_CERT_PATH;
    return `
# ---- ${name} (port ${port}) ----
server {
    listen 80;
    listen [::]:80;
    server_name ${serverName};
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${serverName};
    ssl_certificate     ${certDir}/fullchain.pem;
    ssl_certificate_key ${certDir}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    client_max_body_size 50m;
${location}
}`;
  }

  // HTTP-only — WILDCARD_CERT_DOMAIN not set yet
  return `
# ---- ${name} (port ${port}) ----
server {
    listen 80;
    listen [::]:80;
    server_name ${serverName};
    client_max_body_size 50m;
${location}
}`;
}

// -------------------------------------------------------------------------
// Regenerate projects.conf from the database and reload nginx
// -------------------------------------------------------------------------
async function generateNginxConfig() {
  try {
    const projects = await query(`SELECT name, port FROM projects ORDER BY name`);

    const header = [
      `# Auto-generated by NodeDeploy – do not edit manually`,
      `# Updated: ${new Date().toISOString()}`,
      `# Projects are served at <name>.${BASE_DOMAIN}`,
      `#`,
      `# ONE-TIME SETUP: symlink this file into sites-enabled:`,
      `#   sudo ln -sf ${NGINX_PROJECTS_CONF} /etc/nginx/sites-enabled/nodedeploy-projects.conf`,
      ``,
    ].join('\n');

    const body = projects.length
      ? projects.map(serverBlock).join('\n')
      : '# No projects registered yet\n';

    await fs.writeFile(NGINX_PROJECTS_CONF, header + body + '\n', 'utf8');

    console.log(`[nginx] Wrote ${projects.length} project server block(s) to ${NGINX_PROJECTS_CONF}`);

    await reloadNginx();
    return true;
  } catch (err) {
    console.error('[nginx] generateNginxConfig error:', err.message);
    return false;
  }
}

// -------------------------------------------------------------------------
// Reload nginx (requires sudoers entry – see README)
// -------------------------------------------------------------------------
async function reloadNginx() {
  try {
    await execFileAsync('sudo', ['nginx', '-s', 'reload']);
    console.log('[nginx] Reloaded successfully');
  } catch (err) {
    console.error('[nginx] Reload failed:', err.message);
    console.error('[nginx] Add this to /etc/sudoers (visudo):');
    console.error('[nginx]   %s ALL=(ALL) NOPASSWD: /usr/sbin/nginx -s reload',
      process.env.USER || 'zajako');
  }
}

// -------------------------------------------------------------------------
// Create empty config file on first run so nginx -t never fails
// -------------------------------------------------------------------------
async function ensureConfExists() {
  await fs.mkdir(NGINX_DIR, { recursive: true });

  try {
    await fs.access(NGINX_PROJECTS_CONF);
  } catch {
    await fs.writeFile(NGINX_PROJECTS_CONF, '# Auto-generated by NodeDeploy\n', 'utf8');
    console.log('[nginx] Created', NGINX_PROJECTS_CONF);
  }
}

module.exports = { generateNginxConfig, reloadNginx, ensureConfExists };
