'use strict';

const fs   = require('fs').promises;
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { query } = require('../config/database');

const execFileAsync = promisify(execFile);

const NGINX_DIR = path.join(__dirname, '..', '..', 'nginx');

// Server-block includes (location blocks per project)
const NGINX_PROJECTS_CONF = process.env.NGINX_PROJECTS_CONF ||
  path.join(NGINX_DIR, 'projects.conf');

// Http-block map (WebSocket referer → backend port).
// MUST be included in the http {} block of /etc/nginx/nginx.conf:
//   include /home/zajako/nodeDeploy/nginx/ws-map.conf;
const NGINX_WS_MAP_CONF = process.env.NGINX_WS_MAP_CONF ||
  path.join(NGINX_DIR, 'ws-map.conf');

// -------------------------------------------------------------------------
// Build a pair of location blocks for one project
// -------------------------------------------------------------------------
function locationBlock(project) {
  const name = project.name;
  const port = project.port;

  return `
  # ---- ${name} (port ${port}) ----
  location = /${name} {
    return 301 $scheme://$host/${name}/;
  }
  location /${name}/ {
    proxy_pass            http://127.0.0.1:${port}/;
    proxy_redirect        ~^/(.*)$  /${name}/$1;
    proxy_http_version    1.1;
    proxy_set_header      Upgrade           $http_upgrade;
    proxy_set_header      Connection        "upgrade";
    proxy_set_header      Host              $host;
    proxy_set_header      X-Real-IP         $remote_addr;
    proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      X-Base-Path       /${name};
    proxy_read_timeout    120s;
    proxy_connect_timeout 10s;
  }`;
}

// -------------------------------------------------------------------------
// Build the http-block map that routes root-path WebSocket connections
// to the correct project port based on the Referer header.
//
// When client JS connects to wss://npmdeploy.com/ from a page loaded at
// npmdeploy.com/projectname/, the browser sends:
//   Upgrade: websocket
//   Referer: https://npmdeploy.com/projectname/
// The map key "$http_upgrade:$http_referer" matches this pattern and
// selects the right upstream. All other requests default to the portal.
// -------------------------------------------------------------------------
function wsMapConf(projects) {
  const portalBackend = `http://127.0.0.1:${process.env.PORT || 8080}`;

  const entries = projects.map(p =>
    `    # ${p.name}\n    ~^websocket:https?://[^/]+/${p.name}  http://127.0.0.1:${p.port};`
  ).join('\n');

  return [
    `# Auto-generated by NodeDeploy – do not edit manually`,
    `# Updated: ${new Date().toISOString()}`,
    `#`,
    `# ONE-TIME SETUP: add the following line inside the http { } block of`,
    `# /etc/nginx/nginx.conf  (only needed once):`,
    `#   include ${NGINX_WS_MAP_CONF};`,
    ``,
    `# Maps "$http_upgrade:$http_referer" → upstream backend.`,
    `# Lets root-path WebSocket connections (wss://npmdeploy.com/) from a`,
    `# project page be routed directly to that project's port instead of`,
    `# the portal, without the app needing to know its subpath prefix.`,
    `map $http_upgrade:$http_referer $ndws_backend {`,
    `    default  ${portalBackend};`,
    entries || `    # no projects yet`,
    `}`,
    ``,
  ].join('\n');
}

// -------------------------------------------------------------------------
// Regenerate both config files from the database and reload nginx
// -------------------------------------------------------------------------
async function generateNginxConfig() {
  try {
    const projects = await query(`SELECT name, port FROM projects ORDER BY name`);

    // --- projects.conf (server block) ---
    const projHeader = [
      `# Auto-generated by NodeDeploy – do not edit manually`,
      `# Updated: ${new Date().toISOString()}`,
      ``,
    ].join('\n');

    const projBody = projects.length
      ? projects.map(locationBlock).join('\n')
      : '  # No projects registered yet';

    await fs.writeFile(NGINX_PROJECTS_CONF, projHeader + projBody + '\n', 'utf8');

    // --- ws-map.conf (http block) ---
    await fs.writeFile(NGINX_WS_MAP_CONF, wsMapConf(projects), 'utf8');

    console.log(`[nginx] Wrote ${projects.length} project(s) to configs`);

    await reloadNginx();
    return true;
  } catch (err) {
    console.error('[nginx] generateNginxConfig error:', err.message);
    return false;
  }
}

// -------------------------------------------------------------------------
// Reload nginx (requires sudoers entry – see README)
// -------------------------------------------------------------------------
async function reloadNginx() {
  try {
    await execFileAsync('sudo', ['nginx', '-s', 'reload']);
    console.log('[nginx] Reloaded successfully');
  } catch (err) {
    console.error('[nginx] Reload failed:', err.message);
    console.error('[nginx] Add this to /etc/sudoers (visudo):');
    console.error('[nginx]   %s ALL=(ALL) NOPASSWD: /usr/sbin/nginx -s reload',
      process.env.USER || 'zajako');
  }
}

// -------------------------------------------------------------------------
// Create empty config files on first run so nginx -t never fails
// -------------------------------------------------------------------------
async function ensureConfExists() {
  await fs.mkdir(NGINX_DIR, { recursive: true });

  for (const [file, stub] of [
    [NGINX_PROJECTS_CONF, '# Auto-generated by NodeDeploy\n'],
    [NGINX_WS_MAP_CONF,
      `# Auto-generated by NodeDeploy\nmap $http_upgrade:$http_referer $ndws_backend {\n    default http://127.0.0.1:${process.env.PORT || 8080};\n}\n`
    ],
  ]) {
    try {
      await fs.access(file);
    } catch {
      await fs.writeFile(file, stub, 'utf8');
      console.log('[nginx] Created', file);
    }
  }
}

module.exports = { generateNginxConfig, reloadNginx, ensureConfExists };
