'use strict';

const fs   = require('fs').promises;
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { query } = require('../config/database');

const execFileAsync = promisify(execFile);

// Path to the generated include file.  Must match the `include` directive in
// npmdeploy.com.conf.  Override via env if the portal is installed elsewhere.
const NGINX_PROJECTS_CONF = process.env.NGINX_PROJECTS_CONF ||
  path.join(__dirname, '..', '..', 'nginx', 'projects.conf');

// -------------------------------------------------------------------------
// Build a pair of location blocks for one project
// -------------------------------------------------------------------------
function locationBlock(project) {
  const name = project.name;
  const port = project.port;

  return `
  # ---- ${name} (port ${port}) ----
  location = /${name} {
    return 301 $scheme://$host/${name}/;
  }
  location /${name}/ {
    proxy_pass            http://127.0.0.1:${port}/;
    proxy_redirect        ~^/(.*)$  /${name}/$1;
    proxy_http_version    1.1;
    proxy_set_header      Upgrade           $http_upgrade;
    proxy_set_header      Connection        "upgrade";
    proxy_set_header      Host              $host;
    proxy_set_header      X-Real-IP         $remote_addr;
    proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      X-Base-Path       /${name};
    proxy_read_timeout    120s;
    proxy_connect_timeout 10s;
  }`;
}

// -------------------------------------------------------------------------
// Regenerate projects.conf from the database and reload nginx
// -------------------------------------------------------------------------
async function generateNginxConfig() {
  try {
    // Include all projects so their location blocks exist even while stopped
    // (nginx will get a 502 from the dead port, which is correct behaviour)
    const projects = await query(
      `SELECT name, port FROM projects ORDER BY name`
    );

    const header = [
      `# Auto-generated by NodeDeploy – do not edit manually`,
      `# Updated: ${new Date().toISOString()}`,
      ``,
    ].join('\n');

    const body = projects.length
      ? projects.map(locationBlock).join('\n')
      : '  # No projects registered yet';

    const content = header + body + '\n';

    await fs.writeFile(NGINX_PROJECTS_CONF, content, 'utf8');
    console.log(`[nginx] Wrote ${projects.length} project(s) to ${NGINX_PROJECTS_CONF}`);

    await reloadNginx();
    return true;
  } catch (err) {
    console.error('[nginx] generateNginxConfig error:', err.message);
    return false;
  }
}

// -------------------------------------------------------------------------
// Reload nginx (requires sudoers entry – see README)
// -------------------------------------------------------------------------
async function reloadNginx() {
  try {
    await execFileAsync('sudo', ['nginx', '-s', 'reload']);
    console.log('[nginx] Reloaded successfully');
  } catch (err) {
    console.error('[nginx] Reload failed:', err.message);
    console.error('[nginx] Add this to /etc/sudoers (visudo):');
    console.error('[nginx]   %s ALL=(ALL) NOPASSWD: /usr/sbin/nginx -s reload', process.env.USER || 'zajako');
  }
}

// -------------------------------------------------------------------------
// Create an empty projects.conf on first run so nginx -t doesn't fail
// -------------------------------------------------------------------------
async function ensureConfExists() {
  try {
    await fs.access(NGINX_PROJECTS_CONF);
  } catch {
    await fs.mkdir(path.dirname(NGINX_PROJECTS_CONF), { recursive: true });
    await fs.writeFile(NGINX_PROJECTS_CONF,
      '# Auto-generated by NodeDeploy – do not edit manually\n', 'utf8');
    console.log('[nginx] Created empty', NGINX_PROJECTS_CONF);
  }
}

module.exports = { generateNginxConfig, reloadNginx, ensureConfExists };
